### ISSUE TITLE
Context menu is not usable on tiling window managers

### ISSUE THREAD

**Issue by diovudau** [pdesaulniers/wolf-shaper#106]
Please make the context menu an actual one that has the right Xorg flags.

Your context menu opens as a normal X-Window, which tiling window managers will resize and position somewhere on the screen. In this case as a tiny drawing area with 1000x dead area.

The real problem is that mouse cursor is, of course, still in the plugin area. So if you move the mouse cursor the context-window closes immediately. I would guess you have a check if the mouse focus is not in the context menu and then close it. Which also happens if the mouse cursor was never in the menu to begin with.

**Comment by pdesaulniers** [comment]
Good. In which tiling window manager should I test this in particular? I think it worked OK in xmonad.

**Comment by diovudau** [comment]
I'm using QTile

**Comment by pdesaulniers** [comment]
The context menu seems to behave as expected in QTile now. Can you build from source and confirm? (don't forget to update the submodules)

**Comment by pdesaulniers** [comment]
Closing this :)
