### ISSUE TITLE
[feature request] add a mark next to the current curve type

### ISSUE THREAD

**Issue by trebmuh** [pdesaulniers/wolf-shaper#112]
Actuellement, on a ça :

![wolfshaper](https://user-images.githubusercontent.com/8705846/46111234-89014200-c1e6-11e8-82e1-816bdbea4748.png)

Suggestion :

![wolfshaper2](https://user-images.githubusercontent.com/8705846/46111243-8f8fb980-c1e6-11e8-958f-2b456019bb12.png)

**Comment by sub26nico** [comment]
Je plussoie la proposition de  @trebmuh , j'ai parfois cru que le menu ne fonctionnait pas, 
mais c'est moi qui zappait d'agir sur la forme d'onde. Le point rendrait visible les manips 
précédentes.

**Comment by pdesaulniers** [comment]
Voilà:

![context_menu](https://user-images.githubusercontent.com/23723605/56101670-4f7af480-5ef4-11e9-8ecb-f90a8f0a7bfd.png)

**Comment by trebmuh** [comment]
chouette :+1:
