### ISSUE TITLE
Packaging, contrib files and location

### ISSUE THREAD

**Issue by dvzrv** [pdesaulniers/wolf-shaper#117]
I would like to move the latest stable version of this nice plugin to Arch Linux' [community] repository.
I see you already did some work on trying to ease the work for package maintainers and the like in #42. However, I have some questions and notes on it:

* it doesn't make sense to maintain your PKGBUILD within this repository. The AUR has git repositories per-package for that already and you're actually the [maintainer of the wolf-shaper-git package](https://aur.archlinux.org/packages/wolf-shaper-git/). Detailed build/installation instructions should be enough.
* the XDG desktop file and icon should not be located in `pkg/debian/`, as those files apply to all distros. a `contrib` directory would probably be more reasonable.
* the Debian packaging should be dealt with downstream as well (same reasons as with Arch Linux packaging), or are you building this package and publishing it somewhere?
* as this git repository contains some submodules, it would be great, if you could release a source code version with the submodules already checked out (as reference, have a look at [how this was achieved for supercollider's sc3-plugins](https://github.com/supercollider/sc3-plugins/blob/master/package/create_package.sh)).
* generally I'd also be happy, if you would consider [signing your git tags and/or commits](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work) and/or release tarballs (in the case you implement something similiar as what is noted above regarding the tarballs including the submodules).

**Comment by pdesaulniers** [comment]
> the XDG desktop file and icon...

I would just get rid of those, unless @trebmuh is against it :)

> the Debian packaging should be dealt with downstream as well (same reasons as with Arch Linux packaging), or are you building this package and publishing it somewhere?

I'm using this package for the Ubuntu PPA. I don't know what would be the process to get the package into the main Debian repo, so I'm leaving the package here for now.

I'll look into the other points.

**Comment by trebmuh** [comment]
> the XDG desktop file and icon...
> I would just get rid of those, unless @trebmuh is against it :)

I'll still providing those for LZK but here is your repo, so do as you want.

**Comment by dvzrv** [comment]
@pdesaulniers so far so great! is your pgp public key not on any keyserver though?

**Comment by dvzrv** [comment]
Apart from that: [now in [community]](https://www.archlinux.org/packages/community/x86_64/wolf-shaper/).

**Comment by pdesaulniers** [comment]
Thanks! 

Yes, I forgot to send the key. Should be OK now, I think.

**Comment by pdesaulniers** [comment]
I suppose I can close this :)
