### ISSUE TITLE
Support for Ubuntu 19.10 (Eoan Ermine)

### ISSUE THREAD

**Issue by ScorpIan555** [pdesaulniers/wolf-shaper#125]
I'm actually running Pop_OS (https://github.com/pop-os), a flavor of Ubuntu maintained by hardware manufacturer System76, version 19.10 (Eoan Ermine), however, the package management is exactly the same, so this will apply to Ubuntu 19.10 users as well.

I was able to install and get wolf-shaper working by pointing the install to the disco release.  So far, so good, so obviously this isn't urgent. 

Incidentally, in case anyone else sees this and is curious (and aren't experienced using Linux/Ubuntu/etc), here's some additional info to help you out:

1) I installed wolf-shaper per the instructions in the README, except:
2) Before you add the ppa repository, you have to run sudo apt update (it won't run after).  So just run 'sudo apt update' first, then use the commands in the README.
3)  I then (after install is complete & I played w/ the UI to make sure it was kosher) removed the ppa via `sudo apt-add-repository --remove ppa:<repo-address>`
4)  If you don't do #3, any package you've installed via apt, which is the main package manager you should be using to install most things into Ubuntu, ***WILL NOT UPDATE*** (so #3 is very important if you don't wanna fuck up your shit up).
-- Note: Ardour users are recommended by the core Ardour dev team to not use apt to install, so use Ardour.org's download instructions (they can't support the package on apt).

The alternative to doing this is to go into the /etc/apt/sources.list manually so it points to the disco release instead of eoan.  Suggestion: if you don't know what any of that last sentence means, just do it the way I did (it's easy).

My personal preference is to wait for a repo (of wolf-shaper) dedicated to the release (of Ubuntu) that I'm using.   If you're doing the same, you should subscribe to this post to see when it's closed (then simply add the ppa repo back, update, etc, per the instructions in the README).

If you have any bugs or issues using wolf-shaper after following my instructions (down the line, in the future), make sure you double check the version installed on your computer and ensure it's the most up-to-date version that's been released (meaning: you might have missed an update because your not getting automatic updates thru apt, until you re-add the ppa when this post is closed!)

also:

use your text editor of choice to look at your sources.list file (nano/vim/etc), eg:
`nano /etc/apt/sources.list`

check your installed apps (version number returned in results):

`apt list --installed wolf*`

**Comment by pdesaulniers** [comment]
I've added some binaries for Ubuntu Eoan and Focal. Should be good now!

I wasn't aware that outdated repos could cause some issues as described in point 4. Maybe there's a way to avoid this, but I don't know much about Ubuntu / Debian packaging...

**Comment by pdesaulniers** [comment]
I think I can close this issue. From now on, I will try to keep the PPA up to date for every Ubuntu release.
