### ISSUE TITLE
Bug in Waveform Free windows 10, UI gets bigger each time you close and open the plugin.

### ISSUE THREAD

**Issue by VoodooGlasses** [pdesaulniers/wolf-shaper#126]
Whenever the plugin window in Waveform Free gets closed and reopened it gets bigger, this can get out of hand if not careful so that resize button is off screen.

**Comment by pdesaulniers** [comment]
Thanks for the bug report!

I think I might have fixed this issue in https://github.com/pdesaulniers/wolf-shaper/commit/b7d691bb0f1396078dd2d242b55a41558e371e24. Can you try this build and confirm that everything works fine? 
[wolf-shaper-v0.1.8-windows-vst2.zip](https://github.com/pdesaulniers/wolf-shaper/files/5301878/wolf-shaper-v0.1.8-windows-vst2.zip)

**Comment by VoodooGlasses** [comment]
Thank you so much, this has fixed it!
