### ISSUE TITLE
First switch of wave type often doesn't work

### ISSUE THREAD

**Issue by mkruselj** [pdesaulniers/wolf-shaper#127]
This shouldn't be too difficult to reproduce. But just adding some nodes and trying to change wave types for them, often doesn't work and one needs to try the dropdown menu more than once to get the waveform to actually change.

**Comment by pdesaulniers** [comment]
I believe this issue was fixed in https://github.com/pdesaulniers/wolf-shaper/commit/11a7616a2532ae586cac1f0d21d062186ea55ca5. I will soon push a new release which includes this fix!

**Comment by pdesaulniers** [comment]
OK, this should be fixed in release v0.1.8. Can you confirm that the context menu works fine now?

**Comment by pdesaulniers** [comment]
I believe this issue is fixed. Feel free to reopen the issue if you can still reproduce the bug!
