### ISSUE TITLE
Find a better name for the plugin??

### ISSUE THREAD

**Issue by pdesaulniers** [pdesaulniers/wolf-shaper#21]

**Comment by deadray6** [comment]
spoonieshaper?

**Comment by pdesaulniers** [comment]
Indeed, that would be much better :) But I don't know if I want to keep the "spoonie" part of the name.

**Comment by deadray6** [comment]
It's probably a good idea to find a more brandname-kinda replacement for "spoonie" (or leave it as is) and if it's going to be a "generic" waveshaper, add "shaper" or similar to it. 
E.g. Fruity WaveShaper.

**Comment by deadray6** [comment]
Also, I was thinking about how would I name a plugin collection if it was made by me.
and actually, what I found the best sounding to me is part of the name of my favourite animation character: Owl

**Comment by pdesaulniers** [comment]
It's a three-letter name, which is good, and the symbolism for owls is quite nice. The name is kind of already taken, though: https://hoxtonowl.com/

If we're going for the Super Loud Abrasive Shit™ aesthetic, then we could also pick some edgy words like acid, toxic, poison, venom, or whatever. It would make sense for a distortion plugin, at least.

Really not sure if it's a good idea, I'm just brainstorming :p

**Comment by pdesaulniers** [comment]
Then, wolves are awesome too. Wolf Plugins, Wolf Limiter, Wolf Shaper, Wolf Crusher...

**Comment by deadray6** [comment]
The wolves are gonna eat the Calves.......
