### ISSUE TITLE
Find some ways to make the plugin more unique

### ISSUE THREAD

**Issue by pdesaulniers** [pdesaulniers/wolf-shaper#33]
It's too similar to Fruity WaveShaper.

Here are some ideas:
https://github.com/pdesaulniers/spoonie-waveshaper/issues/19
https://github.com/pdesaulniers/spoonie-waveshaper/issues/20
https://github.com/pdesaulniers/spoonie-waveshaper/issues/34

**Comment by deadray6** [comment]
I would say it's just too similar to a generic waveshaper.

**Comment by deadray6** [comment]
I know something that would make this plugin more usable, it is a feature to allow automation of the vertexes.

**Comment by deadray6** [comment]
And I don't know if it's worth it, but the feature for automatic morphing (e.g. synced with daw or triggered by automations) between N waveshaper presets, where N >= 2.

**Comment by pdesaulniers** [comment]
Both features would be interesting to have and (AFAIK) simple to implement. :)

**Comment by deadray6** [comment]
More complicated thing to implement: multiple waveshaper presets working in one plugin at the same time, each has detune (that would introduce need to compensate latency), dry/wet, panning (and narrower maybe), pregain, postgain (etc) options and resulting into multiple processed sounds, then getting mixed into one sound.

**Comment by deadray6** [comment]
You can call it multivoice waveshaper.

**Comment by deadray6** [comment]
I don't know if it would have an ability to produce decent sounds though.

**Comment by deadray6** [comment]
Simplier feature idea: optional assymetric waveshaping, so negative (below zero) samples would get waveshaped differently from positive (over zero). Or is it the way it works already?

**Comment by pdesaulniers** [comment]
It doesn't work but it's coming: https://github.com/pdesaulniers/spoonie-waveshaper/issues/3

**Comment by deadray6** [comment]
Nice, wow

**Comment by pdesaulniers** [comment]
> automatic morphing (e.g. synced with daw or triggered by automations) between N waveshaper presets, where N >= 2

Should there be any interpolation (crossfading) between the presets? Like, you could turn a knob and it would go through the presets in a fluid manner. There could be some "1 2 3 4" buttons to edit / focus on the actual presets.

**Comment by deadray6** [comment]
I am not sure at all how would you implement interpolation. Coding crossfading is probably easier, but that's not what I meant and wanted. What I meant by morphing would be like real-time transition of curve from A curve to B curve (to C and etc).

**Comment by deadray6** [comment]
As I said, I have no idea how would one implement this, especially if number of vertexes is different on A and B curves.

**Comment by pdesaulniers** [comment]
It could be done at line level, without considering the vertexes. The vertexes could just fade out or something, unless we click on the edit buttons.

Anyway, I don't know if it's a good idea :p

**Comment by deadray6** [comment]
Probably it is

**Comment by pdesaulniers** [comment]
Tons of ideas have been proposed, so I'm closing this.
