### ISSUE TITLE
Add some labels to describe the widgets

### ISSUE THREAD

**Issue by pdesaulniers** [pdesaulniers/wolf-shaper#35]
We'll need some good-looking fonts that are free to use.

**Comment by deadray6** [comment]
How free?

**Comment by deadray6** [comment]
As in what license

**Comment by deadray6** [comment]
as far as I know, bitwig uses http://www.opensans.com/

**Comment by deadray6** [comment]
Apache License 2.0

**Comment by pdesaulniers** [comment]
> As in what license

Anything that's compatible with ISC, I guess.

Open Sans is fine, but I guess it's kind of overused :)

**Comment by deadray6** [comment]
Overused???? if it's good, then why not using it again?

**Comment by pdesaulniers** [comment]
I'm not really against using it, but perhaps some more unusual fonts could be more interesting. 

I think Open Sans Italics would probably be nice for the in/out labels.

**Comment by deadray6** [comment]
Well, I only know popular fonts.. except some monospace fonts

**Comment by deadray6** [comment]
which wont work well..

**Comment by deadray6** [comment]
https://en.wikipedia.org/wiki/Cantarell_(typeface)
https://en.wikipedia.org/wiki/Ubuntu_(typeface)
https://en.wikipedia.org/wiki/Roboto
well i also like these fonts, I don't know how would they work in plugin
