### ISSUE TITLE
Some parametres become default on saving-loading (VST)

### ISSUE THREAD

**Issue by ghost** [pdesaulniers/wolf-shaper#39]
pre-gain, wet, post-gain, oversampling while vertexes save just fine
Bitwig 1.3.15, vst version

**Comment by pdesaulniers** [comment]
Thanks for the report :) I can reproduce the bug in Renoise as well.

**Comment by deadray6** [comment]
No problem
чт, фев 22, 2018 в 20:15, Patrick Desaulniers  написал: 

	Thanks for the report :) I can reproduce the bug in Renoise as well.

**Comment by pdesaulniers** [comment]
Seems like this bug affects DPF plugins that use both states and parameters. For example, ZaMultiComp and ZamHeadX2 seem have the same issue.

**Comment by deadray6** [comment]
okay you finally made me think about that I didn't mention that this happened with vst version

**Comment by pdesaulniers** [comment]
AFAIK, that's the only format bitwig supports :p

**Comment by deadray6** [comment]
Yeah, I could use Carla for some reason and should have mentioned that anyway

**Comment by pdesaulniers** [comment]
Should be fixed now.
