### ISSUE TITLE
Create Linux packages for the plugin

### ISSUE THREAD

**Issue by pdesaulniers** [pdesaulniers/wolf-shaper#42]

**Comment by trebmuh** [comment]
Je peux te faire un PR avec les règles de créations pour un paquet debian si tu veux.

**Comment by pdesaulniers** [comment]
Pardon d'avoir mis du temps à répondre :) 

Connais-tu d'autres projets qui mettent des choses liées aux paquets Linux directement dans leur dépôt git?

**Comment by trebmuh** [comment]
Certains le font (Hydrogen par exemple), d'autres non.

**Comment by pdesaulniers** [comment]
OK, je dirais que ça a du sens :) Tu peux faire un PR.

**Comment by pdesaulniers** [comment]
J'ai fait un dossier pkg.

**Comment by trebmuh** [comment]
PR envoyé.

**Comment by pdesaulniers** [comment]
Got some packages for Arch and Ubuntu. Good enough for now.
