### ISSUE TITLE
Jack build of plugin has high cpu usage when idle

### ISSUE THREAD

**Issue by pdesaulniers** [pdesaulniers/wolf-shaper#60]

**Comment by pdesaulniers** [comment]
The issue seems gone now. I think it was related to the UI being rendered at every idle call. I'll just close this, unless somebody else has that issue.

Still, that stuff about denormals is good to know :)

**Comment by harryhaaren** [comment]
+1 to close, I've tested DSP load here with JACK and haven't seen anything strange.
LV2BM reports the following, with 1.3% DSP load as worse-case, which is very lightweight :)
```
lv2bm --full-test `lv2ls | grep wolf`
Plugin: https://github.com/pdesaulniers/wolf-shaper, Input signal: Sine Wave
    TestName  TotalTime(s)   AvrTime(s)  JackLoad(%)
   MinValues    0.00174035   0.00000464     0.348070
   DefValues    0.00347788   0.00000927     0.695575
   MaxValues    0.00368117   0.00000982     0.736233
  BestResult    0.00166299   0.00000443     0.332598
 WorstResult    0.00671606   0.00001791     1.343212
```
