### ISSUE TITLE
réduire la taille minimale de l'IGU (reduce the minimal GUI size)

### ISSUE THREAD

**Issue by trebmuh** [pdesaulniers/wolf-shaper#66]
La taille minimum de l'IGU est trop grande pour le peu d'infos qu'il peut y avoir, ça pourrait être vraiment bien de pouvoir la réduire.

**Comment by pdesaulniers** [comment]
J'ai mis la taille minimale à 400x453. C'est assez petit? :)

**Comment by trebmuh** [comment]
C'est déjà mieux mais je trouve ça encore top grand. C'est possible de la réduire encore où ça va poser des soucis ?

**Comment by pdesaulniers** [comment]
Ah! je pense avoir trouvé la solution :)

https://github.com/pdesaulniers/wolf-shaper/issues/72

**Comment by trebmuh** [comment]
Ah oué, bonne idée !

**Comment by pdesaulniers** [comment]
OK, je pense que l'IGU ne peut pas être bien plus petite que cela.

**Comment by trebmuh** [comment]
ahhhhhhhhhhhhh !
:)
