### ISSUE TITLE
Better color scheme for UI

### ISSUE THREAD

**Issue by pdesaulniers** [pdesaulniers/wolf-shaper#8]

**Comment by pdesaulniers** [comment]
The UI is quite dark, and the yellow line when an edge is focused is quite ugly.

**Comment by deadray6** [comment]
I may try to work on this. 
[see that ugly pfp, it perfectly describes my experience with colour palletes)

**Comment by deadray6** [comment]
Should I try to separate colours from C(++) files to some XML-like (or .conf-like, etc) theme files?
That would allow choosing between multiple themes and further customization of UI.

**Comment by pdesaulniers** [comment]
That could be neat. Whatever we use for reading the config files must be safe to use in a plugin, though. 

Also, sorry if the UI code is messy. I didn't expect that some people would find out about my plugin so soon :p

**Comment by deadray6** [comment]
Well, I needed a native waveshaper linux vst and searched on github. Was surprised that actually found one.

**Comment by deadray6** [comment]
> must be safe
I'll do some research before trying to implement, of course.

**Comment by deadray6** [comment]
So, after a little bit of research, three solutions: libconfuse (ISC), libconfig (GPLv2.1) - both are Win&Lin only, and as I can see, you support Mac OS X too. 
We can use boost/spirit but it seems too large for this small task

**Comment by deadray6** [comment]
_continues research_

**Comment by deadray6** [comment]
https://github.com/benhoyt/inih (BSD 3-Clause)

**Comment by deadray6** [comment]
I kind of like the last one, let me know what you think

**Comment by pdesaulniers** [comment]
I kind of like it as well :) Let's go with that.

**Comment by deadray6** [comment]
Also, if it's not too big deal, can you please list all the things that are being coloured and corresponding codelines. I mean, I can do that myself, but it would be probably 3 times as time-consuming.

**Comment by deadray6** [comment]
(like that 'abracadabra: line xx in yy.zz" would be great)

**Comment by pdesaulniers** [comment]
Sure, but I'm kind of busy right now. I'll make that list in a few hours if you don't mind :p

**Comment by deadray6** [comment]
anyway I probably won't start coding today, am busy too, but procrastinating as usual

**Comment by pdesaulniers** [comment]
Not sure how we should store the colors. Perhaps something like "rgba(255,255,255,255)" would do the trick? Maybe just comma separated integers? I don't think hex strings are very readable :)

Also, I think it should be possible to reload the config while the program is running to test some colors quickly. 

Anyway, here's the relevant colors and code lines, all in Widgets/src :

**GraphWidget.cpp**

145 – grid_foreground (the grey grid)
146 – grid_background (it's the subtle dark grid behind the grey one, basically its shadow. not sure if necessary)
147 – sub_grid (the black lines that separate the squares in four)
243 – graph_background
319 – alignment_lines (when holding a vertex)
344 – input_volume_indicator
379 – in_out_labels
397 – graph_edges_background_normal and graph_edges_background_emphasized (lines shadow)
398 – graph_edges_foreground_normal and graph_edges_foreground_emphasized (actual line color)

**GraphNode.cpp**

14 – vertex_fill_normal
62 – vertex_stroke_normal (its outline)
395 – tension_handle_color_normal
397 – tension_handle_color_emphasized

There will also be a vertex_fill_emphasized and stroke_color_emphasized soon. I think grabbed vertices will have some sort of halo. They could also have a drop shadow if it looks good.

**GraphWidgetSocket.cpp** (this one's very messy, will change a lot)

43 – plugin_background
60 – graph_margin (or the dead zone of the graph, idk how to call it)
101 – grey lines at the left, bottom and right of the graph
114 – the black line at the top of the graph

It would be nice to throw some subtle gradients in. NanoVG gradients seem to have some banding issues, so we'll avoid them for now. I'll look into it later.

I think we can ignore the other widgets for now.

Some day, it might also be nice to define the size of the vertices, the speed at which the curves bend, the speed of the animations, etc. in the config file as well. It would help for designing the UI, I suppose.

**Comment by deadray6** [comment]
Thank you. I'll note the other stuff you mentioned.
There are some other problems though:
1) how will we bundle https://github.com/benhoyt/inih?
possible solutions:
a. submodule a latest (or not) release source tarball - i prefer this one
b. make a fork following the inih's BSD 3-clause license
c. ???
2) where should we store config files?
possible solutions:
a. next to vst, lv2, dssi, jack executable
problem is that then you would need to have multiple config files for different builds and types of builds of the plugin
b. user-wide directory such as  ~/.config/spoonie-waveshaper
problem is that i have no idea where is the equivalent of such place on windows and mac os x, and actually can't really test the feature on these. though, it seems a better option
c. ???

**Comment by deadray6** [comment]
>possible to reload the config

I am unfamiliar with how UI is built on this plugin, but I can try to add at least a keyboard shortcut.

**Comment by deadray6** [comment]
I'll try to finish this feature till March, though I am always busy studying or wasting time >_<

**Comment by pdesaulniers** [comment]
As long as there's a function to update the config, then I don't mind dealing with the widget or shortcut or whatever :p Anyway:

1. I plan on changing some stuff inside the library (non-static functions could cause some symbols conflicts, if I'm not mistaken) so it would need to be either a fork or a dumb copy-paste into a Libs folder or something. Not sure what's the best.

2. I think the config file should be in the user's home folder, like you've proposed. I think it goes in ~/Library/Preferences on macos. We can just dump it in My Documents on Windows, which is really annoying, but lots of plugins do it :) 

I'd say, just make it work on Linux for now.

**Comment by deadray6** [comment]
I guess the more 'legal' way is to fork, while actually following license terms.

> just make it work on Linux for now.

Yes, sir!

**Comment by pdesaulniers** [comment]
> (sorry for gender assumption whoops)

Haha, no worries :p

I can't see how it would be illegal to just copy-paste it into a folder. Unless I'm mistaken, it just says that we should put the BSD license alongside the library.

**Comment by pdesaulniers** [comment]
>  though I am always busy studying or wasting time >_<

I'm currently doing an internship, so I'm a bit busy as well.

**Comment by deadray6** [comment]
> I plan on changing some stuff inside the library (non-static functions could cause some symbols conflicts, if I'm not mistaken) so it would need to be either a fork or a dumb copy-paste into a Libs folder or something. Not sure what's the best.

Just realised I didn't understand it... By submoduling I meant forking the repo at the release state to your/organisation account and adding it as a submodule to this repo

**Comment by deadray6** [comment]
I thought you was in need to change function declarations

**Comment by pdesaulniers** [comment]
OK, right. You did mention "source tarballs", so I'm the one who misunderstood :p

Well, the second option is a bit weird, since I think it wouldn't be considered "related" to the original like a fork would be. AFAIK, we wouldn't be able to easily update it from the original.

I think forking the repo at the most recent commit and adding it as a submodule makes sense.

**Comment by deadray6** [comment]
Imo, the most recent commit makes it less reliable.

**Comment by deadray6** [comment]
That's why I proposed to use some release-state sources.

**Comment by pdesaulniers** [comment]
The release-state source is the most recent commit as of now.

**Comment by deadray6** [comment]
oh, well, okay

**Comment by deadray6** [comment]
I guess I'll (temporarily?) submodule _my_ fork of the inih library, so I could have access to it.

**Comment by deadray6** [comment]
Like, we don't really need examples/ folder

**Comment by pdesaulniers** [comment]
I've sent you an invite for push access to a fork.

**Comment by deadray6** [comment]
accepted, well, as you probably already know

**Comment by deadray6** [comment]
okay, sorry, i am in a big trouble and this gets very delayed

**Comment by deadray6** [comment]
okay dude, i'm currently breaking away from everything; so i am breaking my promise on implementing this feature ever

**Comment by deadray6** [comment]
sorry

**Comment by pdesaulniers** [comment]
No problem. Thanks for your help :)

**Comment by pdesaulniers** [comment]
I don't plan on changing the color scheme anymore.
