### ISSUE TITLE
UI not showing up on some systems?

### ISSUE THREAD

**Issue by pdesaulniers** [pdesaulniers/wolf-shaper#81]

**Comment by unfa** [comment]
Standalone works fine, in Ardour 5.12 I have a black window though:

![image](https://user-images.githubusercontent.com/491704/39667059-34444dc4-50ae-11e8-8ba1-b0c6c107ea28.png)

Related?

**Comment by pdesaulniers** [comment]
Related: https://github.com/DISTRHO/ProM/issues/1

I'm pretty sure that it shouldn't happen, though.

**Comment by pdesaulniers** [comment]
I might have fixed this for now... Although that fix makes the UI feel very slow in Ardour. 

Can you try it? Make sure you run ```git submodule update``` after pulling :)

**Comment by unfa** [comment]
I've updated form Git master and tried again, same behavior.

I've run Ardour in GDB and adding "Wolf Shaper" LV2 plugin shows this output on GDB:

[New Thread 0x7fff21d49700 (LWP 4251)]
WARNING: this host does not send sample-rate information for LV2 UIs, using 44100 as fallback (this could be wrong)
Can't load 'wolf-shaper.conf', using defaults
[New Thread 0x7fffbedc0700 (LWP 4256)]
[Thread 0x7fffbedc0700 (LWP 4256) exited]

**Comment by pdesaulniers** [comment]
How did you update from git? What's the output of ```git status``` ?

**Comment by unfa** [comment]
Ok, I did `git pull` and compiled again. Looks like it's not enough :D

**Comment by unfa** [comment]
I had to delete the local git repo and reclone it, but it works fine now!

![image](https://user-images.githubusercontent.com/491704/39712193-6bd80850-5222-11e8-9bb6-e5037163f74e.png)
(pardon me the screen tearing n that screenshot)

**Comment by pdesaulniers** [comment]
Sweet! Closing this, thanks.
