### ISSUE TITLE
src/Window.cpp:40:33: fatal error: X11/Xcursor/Xcursor.h: No such file or directory

### ISSUE THREAD

**Issue by unfa** [pdesaulniers/wolf-shaper#84]
I've tried to build Wolf Shaper on a different Linux Mint 18.3 system and I got this:

`src/Window.cpp:40:33: fatal error: X11/Xcursor/Xcursor.h: No such file or directory`

I thought I might be missing some dependencies, but I can't find anything.

**Comment by pdesaulniers** [comment]
Ah, right. You're missing libxcursor-dev :) I'll remove that dependency soon.

**Comment by unfa** [comment]
Ok, installing `libxcursor-dev` seems to help. Though I've stumbled upon another problem.
